import { useState } from "react";
import { CheckCircle2, Gift, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getMonthKey } from "@shared/familyEverydayGood";

export function FamilyMonthlyJoyBox({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [monthKey] = useState(() => getMonthKey()); const [joy, setJoy] = useState(""); const { data: joys = [], isLoading } = trpc.monthlyJoyBoxes.list.useQuery({ familyGroupId, monthKey }, { enabled: familyGroupId > 0 }); const create = trpc.monthlyJoyBoxes.create.useMutation({ onSuccess: async () => { setJoy(""); await utils.monthlyJoyBoxes.list.invalidate({ familyGroupId, monthKey }); } }); const update = trpc.monthlyJoyBoxes.update.useMutation({ onSuccess: () => utils.monthlyJoyBoxes.list.invalidate({ familyGroupId, monthKey }) }); return <Card className="border-0 bg-gradient-to-br from-amber-50 via-white to-orange-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Gift className="h-5 w-5 text-orange-600"/>家族の今月のお楽しみ箱</CardTitle><p className="text-xs text-slate-500">今月やってみたい小さな楽しみを集め、できたら印をつけよう。</p></CardHeader><CardContent className="space-y-3"><div className="flex gap-2 rounded-xl bg-white/80 p-3"><Input value={joy} onChange={(event) => setJoy(event.target.value)} placeholder="例：新しいアイスを一緒に食べる" maxLength={180}/><Button size="sm" disabled={!joy.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, monthKey, joy })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>入れる</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-orange-700">お楽しみを読み込み中です…</p> : <div className="grid gap-2">{joys.map((entry) => <article key={entry.id} className={`rounded-xl p-3 shadow-sm ${entry.isRealized ? "bg-orange-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><p className={`text-sm ${entry.isRealized ? "text-orange-700 line-through" : "font-semibold text-slate-800"}`}>{entry.joy}</p><button type="button" aria-label={entry.isRealized ? "未実現に戻す" : "できた"} onClick={() => update.mutate({ familyGroupId, joyId: entry.id, isRealized: !entry.isRealized })} className={entry.isRealized ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{joys.length === 0 && <p className="rounded-xl border border-dashed border-orange-200 p-3 text-center text-xs text-slate-500">今月、家族で少し楽しみにしたいことを一つ入れてみましょう。</p>}</div>}</CardContent></Card>; }
