import { useState } from "react";
import { CheckCircle2, HandHeart, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getMondayKey } from "@shared/familyCareFlow";

export function FamilyWeeklyCareTheme({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [weekKey] = useState(() => getMondayKey()); const [theme, setTheme] = useState(""); const [careHint, setCareHint] = useState(""); const { data: themes = [], isLoading } = trpc.weeklyCareThemes.list.useQuery({ familyGroupId, weekKey }, { enabled: familyGroupId > 0 }); const create = trpc.weeklyCareThemes.create.useMutation({ onSuccess: async () => { setTheme(""); setCareHint(""); await utils.weeklyCareThemes.list.invalidate({ familyGroupId, weekKey }); } }); const update = trpc.weeklyCareThemes.update.useMutation({ onSuccess: () => utils.weeklyCareThemes.list.invalidate({ familyGroupId, weekKey }) }); return <Card className="border-0 bg-gradient-to-br from-fuchsia-50 via-white to-rose-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><HandHeart className="h-5 w-5 text-fuchsia-700"/>家族の今週の気づかいテーマ</CardTitle><p className="text-xs text-slate-500">今週届けたい小さな気づかいを、やさしく共有しよう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={theme} onChange={(event) => setTheme(event.target.value)} placeholder="例：帰ったら一度、顔を見て声をかける" maxLength={140}/><div className="flex gap-2"><Input value={careHint} onChange={(event) => setCareHint(event.target.value)} placeholder="やり方のヒント（任意）" maxLength={200}/><Button size="sm" disabled={!theme.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, weekKey, theme, careHint })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>決める</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-fuchsia-700">気づかいテーマを読み込み中です…</p> : <div className="grid gap-2">{themes.map((entry) => <article key={entry.id} className={`rounded-xl p-3 shadow-sm ${entry.isActive ? "bg-white" : "bg-fuchsia-50"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm ${entry.isActive ? "font-semibold text-slate-800" : "text-fuchsia-700 line-through"}`}>{entry.theme}</p>{entry.careHint && <p className="mt-1 text-xs text-fuchsia-800">{entry.careHint}</p>}</div><button type="button" aria-label={entry.isActive ? "テーマを終える" : "テーマを再開する"} onClick={() => update.mutate({ familyGroupId, themeId: entry.id, isActive: !entry.isActive })} className={entry.isActive ? "text-slate-400" : "text-emerald-600"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{themes.length === 0 && <p className="rounded-xl border border-dashed border-fuchsia-200 p-3 text-center text-xs text-slate-500">今週、家族へ届けたい小さな気づかいを一つ決めてみましょう。</p>}</div>}</CardContent></Card>; }
