import { useState } from "react";
import { BookmarkCheck, CheckCircle2, Loader2, Plus, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countSavedGoodFinds } from "@shared/familyEverydayGood";

export function FamilyGoodFindMemo({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [goodThing, setGoodThing] = useState(""); const [tag, setTag] = useState(""); const { data: memos = [], isLoading } = trpc.goodFindMemos.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.goodFindMemos.create.useMutation({ onSuccess: async () => { setGoodThing(""); setTag(""); await utils.goodFindMemos.list.invalidate({ familyGroupId }); } }); const update = trpc.goodFindMemos.update.useMutation({ onSuccess: () => utils.goodFindMemos.list.invalidate({ familyGroupId }) }); return <Card className="border-0 bg-gradient-to-br from-lime-50 via-white to-emerald-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Sparkles className="h-5 w-5 text-emerald-700"/>家族の見つけたいいことメモ</CardTitle><p className="text-xs text-slate-500">日常で見つけた良いことを残して、あとから見返そう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-emerald-700"><BookmarkCheck className="mr-1 inline h-4 w-4"/>保存したいいこと：{countSavedGoodFinds(memos)}件</p><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={goodThing} onChange={(event) => setGoodThing(event.target.value)} placeholder="例：帰り道にきれいな夕焼けが見えた" maxLength={240}/><div className="flex gap-2"><Input value={tag} onChange={(event) => setTag(event.target.value)} placeholder="タグ（任意）" maxLength={80}/><Button size="sm" disabled={!goodThing.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, goodThing, tag })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>残す</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-emerald-700">いいことを読み込み中です…</p> : <div className="grid gap-2">{memos.map((memo) => <article key={memo.id} className={`rounded-xl p-3 shadow-sm ${memo.isSaved ? "bg-emerald-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div>{memo.tag && <p className="text-[11px] font-medium text-emerald-800">{memo.tag}</p>}<p className={`mt-1 text-sm ${memo.isSaved ? "text-emerald-700 line-through" : "text-slate-800"}`}>{memo.goodThing}</p></div><button type="button" aria-label={memo.isSaved ? "保存を外す" : "保存する"} onClick={() => update.mutate({ familyGroupId, memoId: memo.id, isSaved: !memo.isSaved })} className={memo.isSaved ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{memos.length === 0 && <p className="rounded-xl border border-dashed border-emerald-200 p-3 text-center text-xs text-slate-500">今日見つけた小さな良いことを、一つ残してみましょう。</p>}</div>}</CardContent></Card>; }
