import { useState } from "react";
import { CheckCircle2, HandHeart, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countHelpfulHands } from "@shared/familyGentleWeekend";

export function FamilyHelpingHand({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [situation, setSituation] = useState(""); const [smallAction, setSmallAction] = useState(""); const { data: hands = [], isLoading } = trpc.helpingHands.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.helpingHands.create.useMutation({ onSuccess: async () => { setSituation(""); setSmallAction(""); await utils.helpingHands.list.invalidate({ familyGroupId }); } }); const update = trpc.helpingHands.update.useMutation({ onSuccess: () => utils.helpingHands.list.invalidate({ familyGroupId }) }); return <Card className="border-0 bg-gradient-to-br from-blue-50 via-white to-indigo-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><HandHeart className="h-5 w-5 text-indigo-700"/>家族の小さな助け舟</CardTitle><p className="text-xs text-slate-500">困ったときに試せる小さな行動を、家族で共有しよう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-indigo-700">役に立った助け舟：{countHelpfulHands(hands)}件</p><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={situation} onChange={(event) => setSituation(event.target.value)} placeholder="例：宿題が進まないとき" maxLength={160}/><div className="flex gap-2"><Input value={smallAction} onChange={(event) => setSmallAction(event.target.value)} placeholder="例：5分だけ一緒に机に座る" maxLength={240}/><Button size="sm" disabled={!situation.trim() || !smallAction.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, situation, smallAction })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>渡す</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-indigo-700">助け舟を読み込み中です…</p> : <div className="grid gap-2">{hands.map((hand) => <article key={hand.id} className={`rounded-xl p-3 shadow-sm ${hand.isHelpful ? "bg-indigo-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className="text-[11px] font-medium text-indigo-800">{hand.situation}</p><p className={`mt-1 text-sm ${hand.isHelpful ? "text-indigo-700 line-through" : "font-semibold text-slate-800"}`}>{hand.smallAction}</p></div><button type="button" aria-label={hand.isHelpful ? "未確認に戻す" : "役に立った"} onClick={() => update.mutate({ familyGroupId, handId: hand.id, isHelpful: !hand.isHelpful })} className={hand.isHelpful ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{hands.length === 0 && <p className="rounded-xl border border-dashed border-indigo-200 p-3 text-center text-xs text-slate-500">困ったときに少し楽になる方法を、一つ共有してみましょう。</p>}</div>}</CardContent></Card>; }
