import { useState } from "react";
import { CheckCircle2, Loader2, Plus, Repeat2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countOpenItems } from "@shared/familyDailyBoard";

export function FamilyRoleBaton({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [task, setTask] = useState(""); const [nextPerson, setNextPerson] = useState(""); const { data: batons = [], isLoading } = trpc.roleBatons.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.roleBatons.create.useMutation({ onSuccess: async () => { setTask(""); setNextPerson(""); await utils.roleBatons.list.invalidate({ familyGroupId }); } }); const update = trpc.roleBatons.update.useMutation({ onSuccess: () => utils.roleBatons.list.invalidate({ familyGroupId }) }); return <Card className="border-0 bg-gradient-to-br from-cyan-50 via-white to-blue-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Repeat2 className="h-5 w-5 text-cyan-700"/>家族の小さな役割バトン</CardTitle><p className="text-xs text-slate-500">今日の小さな役割を引き継いで、終わったら印を付けよう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-cyan-700">引き継ぎ待ち：{countOpenItems(batons.map((item) => ({ completed: item.isCompleted })))}件</p><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={task} onChange={(event) => setTask(event.target.value)} placeholder="例：夕食の食器をしまう" maxLength={180}/><div className="flex gap-2"><Input value={nextPerson} onChange={(event) => setNextPerson(event.target.value)} placeholder="次にお願いしたい人（任意）" maxLength={80}/><Button size="sm" disabled={!task.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, task, nextPerson })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>渡す</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-cyan-700">役割バトンを読み込み中です…</p> : <div className="grid gap-2">{batons.map((baton) => <article key={baton.id} className={`rounded-xl p-3 shadow-sm ${baton.isCompleted ? "bg-cyan-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm ${baton.isCompleted ? "text-cyan-700 line-through" : "font-semibold text-slate-800"}`}>{baton.task}</p>{baton.nextPerson && <p className="mt-1 text-xs text-cyan-800">次は {baton.nextPerson} さんへ</p>}</div><button type="button" aria-label={baton.isCompleted ? "未完了に戻す" : "完了にする"} onClick={() => update.mutate({ familyGroupId, batonId: baton.id, isCompleted: !baton.isCompleted })} className={baton.isCompleted ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{batons.length === 0 && <p className="rounded-xl border border-dashed border-cyan-200 p-3 text-center text-xs text-slate-500">小さな手伝いを一つ、次の人へ渡してみましょう。</p>}</div>}</CardContent></Card>; }
