import { useState } from "react";
import { CheckCircle2, HandHeart, Loader2, MessageCircleQuestion, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { getConsultationKindLabel, type ConsultationKind } from "@shared/familySupportCircle";

export function FamilyConsultationCard({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [kind, setKind] = useState<ConsultationKind>("listen"); const [title, setTitle] = useState(""); const [detail, setDetail] = useState("");
  const { data: cards = [], isLoading } = trpc.consultations.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.consultations.create.useMutation({ onSuccess: async () => { setTitle(""); setDetail(""); setKind("listen"); await utils.consultations.list.invalidate({ familyGroupId }); } });
  const update = trpc.consultations.update.useMutation({ onSuccess: () => utils.consultations.list.invalidate({ familyGroupId }) });
  return <Card className="border-0 bg-gradient-to-br from-indigo-50 via-white to-violet-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><MessageCircleQuestion className="h-5 w-5 text-indigo-600"/>家族の今日の相談カード</CardTitle><p className="text-xs text-slate-500">困ったことや聞いてほしいことを、安心して共有しよう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><div className="grid grid-cols-3 gap-1.5">{(["listen", "advice", "help"] as ConsultationKind[]).map((item) => <button key={item} type="button" onClick={() => setKind(item)} className={`rounded-lg p-2 text-xs ${kind === item ? "bg-indigo-100 text-indigo-800 ring-2 ring-indigo-300" : "bg-white text-slate-600 shadow-sm"}`}>{getConsultationKindLabel(item)}</button>)}</div><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例：明日の発表が少し心配" maxLength={160}/><Textarea value={detail} onChange={(event) => setDetail(event.target.value)} placeholder="もう少し伝えたいこと（任意）" maxLength={500} className="min-h-16"/><Button size="sm" disabled={!title.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, kind, title, detail })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>家族に伝える</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-indigo-700">相談カードを読み込み中です…</p> : <div className="grid gap-2">{cards.map((card) => <article key={card.id} className={`rounded-xl p-3 shadow-sm ${card.isResolved ? "bg-slate-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm font-semibold ${card.isResolved ? "text-slate-500 line-through" : "text-slate-800"}`}>{card.title}</p><p className="mt-0.5 text-[11px] text-indigo-700">{getConsultationKindLabel(card.kind as ConsultationKind)}</p>{card.detail && <p className="mt-1 text-xs text-slate-600">{card.detail}</p>}</div><button type="button" disabled={update.isPending} aria-label={card.isResolved ? "未解決に戻す" : "気持ちが落ち着いた"} onClick={() => update.mutate({ familyGroupId, cardId: card.id, isResolved: !card.isResolved })} className={card.isResolved ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{cards.length === 0 && <p className="rounded-xl border border-dashed border-indigo-200 p-3 text-center text-xs text-slate-500">誰かに聞いてほしいことを、気軽に書いてみましょう。</p>}</div>}</CardContent></Card>;
}
