import { useState } from "react";
import { CheckCircle2, ChefHat, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

const statusLabel = { open: "リクエスト中", planned: "つくる予定", served: "できあがり" } as const;

export function FamilyMealRequest({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [dishName, setDishName] = useState(""); const [reason, setReason] = useState("");
  const { data: requests = [], isLoading } = trpc.mealRequests.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.mealRequests.create.useMutation({ onSuccess: async () => { setDishName(""); setReason(""); await utils.mealRequests.list.invalidate({ familyGroupId }); } });
  const updateStatus = trpc.mealRequests.updateStatus.useMutation({ onSuccess: () => utils.mealRequests.list.invalidate({ familyGroupId }) });
  return <Card className="border-0 bg-gradient-to-br from-orange-50 via-white to-rose-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><ChefHat className="h-5 w-5 text-orange-600"/>家族のひとこと献立リクエスト</CardTitle><p className="text-xs text-slate-500">食べたいものと理由を気軽に伝えて、食卓の会話に。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={dishName} onChange={(event) => setDishName(event.target.value)} placeholder="例：あったかいうどん" maxLength={160}/><Input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="理由（例：今日はちょっと寒かったから）" maxLength={240}/><Button size="sm" disabled={!dishName.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, dishName, reason })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>リクエストする</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-orange-700">献立リクエストを読み込み中です…</p> : <div className="grid gap-2">{requests.map((request) => <article key={request.id} className={`rounded-xl p-3 shadow-sm ${request.status === "served" ? "bg-orange-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-semibold text-slate-800">{request.dishName}</p><p className="mt-0.5 text-[11px] text-orange-700">{statusLabel[request.status]}</p>{request.reason && <p className="mt-1 text-xs text-slate-600">{request.reason}</p>}</div><div className="flex flex-col gap-1">{request.status === "open" && <Button size="sm" variant="outline" disabled={updateStatus.isPending} onClick={() => updateStatus.mutate({ familyGroupId, requestId: request.id, status: "planned" })}>予定にする</Button>}{request.status !== "served" && <Button size="sm" variant="outline" disabled={updateStatus.isPending} onClick={() => updateStatus.mutate({ familyGroupId, requestId: request.id, status: "served" })}><CheckCircle2 className="mr-1 h-3.5 w-3.5"/>できた</Button>}</div></div></article>)}{requests.length === 0 && <p className="rounded-xl border border-dashed border-orange-200 p-3 text-center text-xs text-slate-500">食べたい一品を、最初にリクエストしてみましょう。</p>}</div>}</CardContent></Card>;
}
