import { useState } from "react";
import { CheckCircle2, Loader2, MapPin, Plus, Shirt } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

export function FamilyMeetingMarker({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [locationHint, setLocationHint] = useState(""); const [appearanceHint, setAppearanceHint] = useState(""); const [note, setNote] = useState("");
  const { data: markers = [], isLoading } = trpc.meetingMarkers.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.meetingMarkers.create.useMutation({ onSuccess: async () => { setLocationHint(""); setAppearanceHint(""); setNote(""); await utils.meetingMarkers.list.invalidate({ familyGroupId }); } });
  const update = trpc.meetingMarkers.update.useMutation({ onSuccess: () => utils.meetingMarkers.list.invalidate({ familyGroupId }) });
  return <Card className="border-0 bg-gradient-to-br from-sky-50 via-white to-cyan-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><MapPin className="h-5 w-5 text-sky-700"/>家族のやさしい待ち合わせ目印</CardTitle><p className="text-xs text-slate-500">集合場所で見つけやすい目印や服装を、短く共有しよう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={locationHint} onChange={(event) => setLocationHint(event.target.value)} placeholder="例：駅の改札を出て右の時計の下" maxLength={160}/><div className="grid grid-cols-2 gap-2"><Input value={appearanceHint} onChange={(event) => setAppearanceHint(event.target.value)} placeholder="服装・持ち物（任意）" maxLength={160}/><Input value={note} onChange={(event) => setNote(event.target.value)} placeholder="ひとこと（任意）" maxLength={180}/></div><Button size="sm" disabled={!locationHint.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, locationHint, appearanceHint, note })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>目印を共有</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-sky-700">目印を読み込み中です…</p> : <div className="grid gap-2">{markers.map((marker) => <article key={marker.id} className={`rounded-xl p-3 shadow-sm ${marker.isActive ? "bg-white" : "bg-slate-50"}`}><div className="flex items-start justify-between gap-2"><div><p className={`flex gap-1 text-sm font-semibold ${marker.isActive ? "text-slate-800" : "text-slate-500 line-through"}`}><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-sky-700"/>{marker.locationHint}</p>{marker.appearanceHint && <p className="mt-1 flex gap-1 text-xs text-sky-800"><Shirt className="h-3.5 w-3.5"/>{marker.appearanceHint}</p>}{marker.note && <p className="mt-1 text-xs text-slate-600">{marker.note}</p>}</div><button type="button" aria-label={marker.isActive ? "目印を終了する" : "目印を再開する"} onClick={() => update.mutate({ familyGroupId, markerId: marker.id, isActive: !marker.isActive })} className={marker.isActive ? "text-slate-400" : "text-emerald-600"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{markers.length === 0 && <p className="rounded-xl border border-dashed border-sky-200 p-3 text-center text-xs text-slate-500">待ち合わせが少し楽になる目印を、最初に一つ残しましょう。</p>}</div>}</CardContent></Card>;
}
