import { useState } from "react";
import { Check, Leaf, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getSeasonLabel, type SeasonKind } from "@shared/familySupportCircle";

export function FamilySeasonalIdeas({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [season, setSeason] = useState<SeasonKind>("anytime"); const [title, setTitle] = useState(""); const [note, setNote] = useState("");
  const { data: ideas = [], isLoading } = trpc.seasonalIdeas.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.seasonalIdeas.create.useMutation({ onSuccess: async () => { setSeason("anytime"); setTitle(""); setNote(""); await utils.seasonalIdeas.list.invalidate({ familyGroupId }); } });
  const update = trpc.seasonalIdeas.update.useMutation({ onSuccess: () => utils.seasonalIdeas.list.invalidate({ familyGroupId }) });
  return <Card className="border-0 bg-gradient-to-br from-emerald-50 via-white to-lime-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Leaf className="h-5 w-5 text-emerald-600"/>家族の季節のやってみたいこと</CardTitle><p className="text-xs text-slate-500">季節ごとの小さな体験を集めて、次の予定候補にしよう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><div className="grid grid-cols-5 gap-1">{(["spring", "summer", "autumn", "winter", "anytime"] as SeasonKind[]).map((item) => <button key={item} type="button" onClick={() => setSeason(item)} className={`rounded-lg p-1.5 text-[11px] ${season === item ? "bg-emerald-100 text-emerald-800 ring-2 ring-emerald-300" : "bg-white text-slate-600 shadow-sm"}`}>{getSeasonLabel(item)}</button>)}</div><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例：秋の落ち葉を見に行く" maxLength={160}/><Input value={note} onChange={(event) => setNote(event.target.value)} placeholder="ひとこと（任意）" maxLength={240}/><Button size="sm" disabled={!title.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, season, title, note })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>やってみたいことを追加</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-emerald-700">体験案を読み込み中です…</p> : <div className="grid gap-2">{ideas.map((idea) => <article key={idea.id} className={`rounded-xl p-3 shadow-sm ${idea.isPlanned ? "bg-emerald-100" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm font-semibold ${idea.isPlanned ? "text-emerald-900 line-through" : "text-slate-800"}`}>{idea.title}</p><p className="mt-0.5 text-[11px] text-emerald-700">{getSeasonLabel(idea.season as SeasonKind)}</p>{idea.note && <p className="mt-1 text-xs text-slate-600">{idea.note}</p>}</div><button type="button" disabled={update.isPending} aria-label={idea.isPlanned ? "候補に戻す" : "予定候補にする"} onClick={() => update.mutate({ familyGroupId, ideaId: idea.id, isPlanned: !idea.isPlanned })} className={idea.isPlanned ? "text-emerald-700" : "text-slate-400"}><Check className="h-5 w-5"/></button></div></article>)}{ideas.length === 0 && <p className="rounded-xl border border-dashed border-emerald-200 p-3 text-center text-xs text-slate-500">次の季節にやってみたいことを一つ書いてみましょう。</p>}</div>}</CardContent></Card>;
}
