import { useState } from "react";
import { CheckCircle2, Clock3, Loader2, MapPin, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getNextWeekendDate } from "@shared/familyMorningWeekends";

export function FamilyWeekendHomecomingPlan({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [dateTime, setDateTime] = useState(() => getNextWeekendDate().toISOString().slice(0, 16)); const [meetingPlace, setMeetingPlace] = useState(""); const [note, setNote] = useState("");
  const { data: plans = [], isLoading } = trpc.weekendHomecomingPlans.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.weekendHomecomingPlans.create.useMutation({ onSuccess: async () => { setMeetingPlace(""); setNote(""); await utils.weekendHomecomingPlans.list.invalidate({ familyGroupId }); } });
  const update = trpc.weekendHomecomingPlans.update.useMutation({ onSuccess: () => utils.weekendHomecomingPlans.list.invalidate({ familyGroupId }) });
  return <Card className="border-0 bg-gradient-to-br from-indigo-50 via-white to-sky-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Clock3 className="h-5 w-5 text-indigo-700"/>家族の週末おかえり計画</CardTitle><p className="text-xs text-slate-500">帰宅や集合の目安を共有して、ゆとりある再会にしよう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input type="datetime-local" value={dateTime} onChange={(event) => setDateTime(event.target.value)} aria-label="帰宅または集合の目安"/><Input value={meetingPlace} onChange={(event) => setMeetingPlace(event.target.value)} placeholder="集合場所（任意）" maxLength={160}/><div className="flex gap-2"><Input value={note} onChange={(event) => setNote(event.target.value)} placeholder="ひとこと（任意）" maxLength={240}/><Button size="sm" disabled={!dateTime || create.isPending} onClick={() => create.mutate({ familyGroupId, plannedAt: new Date(dateTime), meetingPlace, note })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>共有</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-indigo-700">週末の計画を読み込み中です…</p> : <div className="grid gap-2">{plans.slice(0, 5).map((plan) => <article key={plan.id} className={`rounded-xl p-3 shadow-sm ${plan.isConfirmed ? "bg-indigo-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className="flex items-center gap-1 text-sm font-semibold text-slate-800"><Clock3 className="h-4 w-4 text-indigo-700"/>{new Date(plan.plannedAt).toLocaleString()}</p>{plan.meetingPlace && <p className="mt-1 flex items-center gap-1 text-xs text-indigo-800"><MapPin className="h-3.5 w-3.5"/>{plan.meetingPlace}</p>}{plan.note && <p className="mt-1 text-xs text-slate-600">{plan.note}</p>}</div><button type="button" aria-label={plan.isConfirmed ? "未確認に戻す" : "確認した"} onClick={() => update.mutate({ familyGroupId, planId: plan.id, isConfirmed: !plan.isConfirmed })} className={plan.isConfirmed ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{plans.length === 0 && <p className="rounded-xl border border-dashed border-indigo-200 p-3 text-center text-xs text-slate-500">次の週末、会える目安を一つ共有してみましょう。</p>}</div>}</CardContent></Card>;
}
