import { useState } from "react";
import { CheckCircle2, HeartHandshake, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countUnreadAppreciation } from "@shared/familyConnectionFlow";

export function FamilyAppreciationCard({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [recipientName, setRecipientName] = useState(""); const [message, setMessage] = useState(""); const { data: cards = [], isLoading } = trpc.appreciationCards.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.appreciationCards.create.useMutation({ onSuccess: async () => { setRecipientName(""); setMessage(""); await utils.appreciationCards.list.invalidate({ familyGroupId }); } }); const update = trpc.appreciationCards.update.useMutation({ onSuccess: () => utils.appreciationCards.list.invalidate({ familyGroupId }) }); return <Card className="border-0 bg-gradient-to-br from-rose-50 via-white to-pink-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><HeartHandshake className="h-5 w-5 text-rose-600"/>家族のお疲れさまカード</CardTitle><p className="text-xs text-slate-500">頑張った人へ、短い「お疲れさま」をそっと届けよう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-rose-700">まだ見ていないカード：{countUnreadAppreciation(cards)}枚</p><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={recipientName} onChange={(event) => setRecipientName(event.target.value)} placeholder="届けたい人の名前" maxLength={80}/><div className="flex gap-2"><Input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="例：今日もお疲れさま、助かったよ" maxLength={220}/><Button size="sm" disabled={!recipientName.trim() || !message.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, recipientName, message })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>届ける</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-rose-700">お疲れさまカードを読み込み中です…</p> : <div className="grid gap-2">{cards.map((card) => <article key={card.id} className={`rounded-xl p-3 shadow-sm ${card.isSeen ? "bg-rose-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold text-rose-600">{card.recipientName} さんへ</p><p className={`mt-1 text-sm ${card.isSeen ? "text-rose-700 line-through" : "font-semibold text-slate-800"}`}>{card.message}</p></div><button type="button" aria-label={card.isSeen ? "未読に戻す" : "受け取った"} onClick={() => update.mutate({ familyGroupId, cardId: card.id, isSeen: !card.isSeen })} className={card.isSeen ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{cards.length === 0 && <p className="rounded-xl border border-dashed border-rose-200 p-3 text-center text-xs text-slate-500">今日頑張っていた人に、ひとこと届けてみましょう。</p>}</div>}</CardContent></Card>; }
