import { useState } from "react";
import { CheckCircle2, Heart, Loader2, Plus, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countCompletedPromises, getMondayKey } from "@shared/familyGentleConnection";

export function FamilyWeeklyPromise({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [weekKey] = useState(() => getMondayKey()); const [title, setTitle] = useState(""); const [note, setNote] = useState("");
  const { data: promises = [], isLoading } = trpc.weeklyPromises.list.useQuery({ familyGroupId, weekKey }, { enabled: familyGroupId > 0 });
  const create = trpc.weeklyPromises.create.useMutation({ onSuccess: async () => { setTitle(""); setNote(""); await utils.weeklyPromises.list.invalidate({ familyGroupId, weekKey }); } });
  const update = trpc.weeklyPromises.update.useMutation({ onSuccess: () => utils.weeklyPromises.list.invalidate({ familyGroupId, weekKey }) });
  return <Card className="border-0 bg-gradient-to-br from-rose-50 via-white to-pink-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Heart className="h-5 w-5 fill-rose-500 text-rose-500"/>家族の今週の小さな約束</CardTitle><p className="text-xs text-slate-500">無理のない一つを決めて、できたら静かに喜ぼう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-rose-700"><Sparkles className="mr-1 inline h-4 w-4"/>今週できた約束：{countCompletedPromises(promises)}件</p><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例：夜に一度、今日のことを聞く" maxLength={160}/><div className="flex gap-2"><Input value={note} onChange={(event) => setNote(event.target.value)} placeholder="やさしい補足（任意）" maxLength={240}/><Button size="sm" disabled={!title.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, weekKey, title, note })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>約束する</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-rose-700">約束を読み込み中です…</p> : <div className="grid gap-2">{promises.map((promise) => <article key={promise.id} className={`rounded-xl p-3 shadow-sm ${promise.isCompleted ? "bg-rose-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm font-semibold ${promise.isCompleted ? "text-rose-700 line-through" : "text-slate-800"}`}>{promise.title}</p>{promise.note && <p className="mt-1 text-xs text-slate-600">{promise.note}</p>}</div><button type="button" aria-label={promise.isCompleted ? "未完了に戻す" : "できた"} onClick={() => update.mutate({ familyGroupId, promiseId: promise.id, isCompleted: !promise.isCompleted })} className={promise.isCompleted ? "text-rose-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{promises.length === 0 && <p className="rounded-xl border border-dashed border-rose-200 p-3 text-center text-xs text-slate-500">「できたらうれしい」くらいの小さな約束を一つ決めましょう。</p>}</div>}</CardContent></Card>;
}
