import { useState } from "react";
import { ChefHat, CheckCircle2, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

export function FamilyMealRelay({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [title, setTitle] = useState(""); const [note, setNote] = useState(""); const [ideaType, setIdeaType] = useState<"want" | "can_make">("want");
  const { data: ideas = [], isLoading } = trpc.mealRelay.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const refresh = () => utils.mealRelay.list.invalidate({ familyGroupId }); const create = trpc.mealRelay.create.useMutation({ onSuccess: async () => { setTitle(""); setNote(""); await refresh(); } }); const select = trpc.mealRelay.select.useMutation({ onSuccess: refresh });
  return <Card className="border-0 bg-gradient-to-br from-rose-50 via-white to-orange-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><ChefHat className="h-5 w-5 text-rose-600"/>家族の献立リレー</CardTitle><p className="text-xs text-slate-500">「食べたい」と「つくれる」をつないで、今日の一品を決めよう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例：野菜たっぷりカレー" maxLength={160}/><Input value={note} onChange={(event) => setNote(event.target.value)} placeholder="ひとこと（任意）" maxLength={240}/><select value={ideaType} onChange={(event) => setIdeaType(event.target.value as "want" | "can_make")} className="h-9 rounded-md border bg-white px-3 text-sm"><option value="want">食べたい</option><option value="can_make">つくれる</option></select><Button size="sm" disabled={!title.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, title, note, ideaType })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <Plus className="mr-1 h-4 w-4"/>}献立案をつなぐ</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-rose-700">献立案を読み込み中です…</p> : <div className="grid gap-2">{ideas.map((idea) => <div key={idea.id} className={`rounded-xl p-3 shadow-sm ${idea.isSelected ? "bg-rose-100" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><span className="text-[10px] text-rose-700">{idea.ideaType === "want" ? "食べたい" : "つくれる"}</span><p className="text-sm font-semibold text-slate-800">{idea.title}</p>{idea.note && <p className="mt-1 text-xs text-slate-600">{idea.note}</p>}</div><Button size="sm" variant={idea.isSelected ? "default" : "outline"} disabled={idea.isSelected || select.isPending} onClick={() => select.mutate({ familyGroupId, mealIdeaId: idea.id })}>{idea.isSelected ? <><CheckCircle2 className="mr-1 h-4 w-4"/>今日の一品</> : "これにする"}</Button></div></div>)}{ideas.length === 0 && <p className="rounded-xl border border-dashed border-rose-200 p-3 text-center text-xs text-slate-500">今夜の一品を、だれかが最初に提案してみましょう。</p>}</div>}</CardContent></Card>;
}
