import { useState } from "react";
import { BarChart3, Loader2, Plus, Vote } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";

export function FamilyPollPanel({ familyGroupId }: { familyGroupId: number }) {
  const [question, setQuestion] = useState(""); const [first, setFirst] = useState(""); const [second, setSecond] = useState("");
  const utils = trpc.useUtils();
  const { data: polls = [], isLoading } = trpc.familyPoll.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0, refetchInterval: 30_000 });
  const create = trpc.familyPoll.create.useMutation({ onSuccess: async () => { setQuestion(""); setFirst(""); setSecond(""); await utils.familyPoll.list.invalidate({ familyGroupId }); toast.success("家族アンケートを共有しました"); }, onError: (error) => toast.error(error.message) });
  const answer = trpc.familyPoll.answer.useMutation({ onSuccess: async () => { await utils.familyPoll.list.invalidate({ familyGroupId }); }, onError: (error) => toast.error(error.message) });
  const endsAt = () => new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString();
  return <Card className="border-0 bg-gradient-to-br from-sky-50 via-white to-cyan-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base text-slate-800"><BarChart3 className="h-5 w-5 text-sky-600" />やさしい家族アンケート</CardTitle><p className="text-xs text-slate-500">名前を出さずに、みんなの気分や希望を集めます。</p></CardHeader><CardContent className="space-y-3"><div className="space-y-2 rounded-2xl bg-white p-3 shadow-sm"><Input value={question} onChange={(event) => setQuestion(event.target.value)} maxLength={240} placeholder="今週末、何をしたい？" /><div className="flex gap-2"><Input value={first} onChange={(event) => setFirst(event.target.value)} maxLength={80} placeholder="選択肢1" /><Input value={second} onChange={(event) => setSecond(event.target.value)} maxLength={80} placeholder="選択肢2" /></div><Button className="w-full" disabled={!question.trim() || !first.trim() || !second.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, question, options: [first, second], endsAt: endsAt() })}>{create.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />}アンケートを作る</Button></div>{isLoading ? <div className="flex justify-center py-4 text-xs text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin" />読み込み中…</div> : <div className="space-y-3">{polls.slice(0, 3).map((poll) => <div key={poll.id} className="rounded-xl bg-white/85 p-3 shadow-sm"><p className="text-sm font-semibold text-slate-800">{poll.question}</p><p className="mt-1 text-[10px] text-slate-500">{poll.responseCount}件の回答・{new Date(poll.endsAt).toLocaleDateString()}まで</p><div className="mt-2 space-y-2">{poll.options.map((option, index) => { const percent = poll.responseCount ? Math.round((poll.counts[index] / poll.responseCount) * 100) : 0; return <button type="button" key={option} disabled={poll.ownOptionIndex !== null || new Date(poll.endsAt) < new Date()} onClick={() => answer.mutate({ pollId: poll.id, optionIndex: index })} className={`w-full rounded-lg p-2 text-left text-xs ${poll.ownOptionIndex === index ? "bg-sky-100 ring-1 ring-sky-300" : "bg-slate-50 hover:bg-sky-50"}`}><span className="flex justify-between"><span>{option}</span><span>{percent}%</span></span><Progress value={percent} className="mt-1.5 h-1.5" /></button>; })}</div>{poll.ownOptionIndex !== null && <p className="mt-2 flex items-center gap-1 text-[10px] text-sky-700"><Vote className="h-3 w-3" />あなたの回答は匿名集計済みです</p>}</div>)}</div>}</CardContent></Card>;
}
