import { useState } from "react";
import { BookHeart, CheckCircle2, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getDailyKey } from "@shared/familyConnectionFlow";

export function FamilyJournalRelay({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [dailyKey] = useState(() => getDailyKey()); const [entry, setEntry] = useState(""); const { data: entries = [], isLoading } = trpc.journalRelayEntries.list.useQuery({ familyGroupId, dailyKey }, { enabled: familyGroupId > 0 }); const create = trpc.journalRelayEntries.create.useMutation({ onSuccess: async () => { setEntry(""); await utils.journalRelayEntries.list.invalidate({ familyGroupId, dailyKey }); } }); const update = trpc.journalRelayEntries.update.useMutation({ onSuccess: () => utils.journalRelayEntries.list.invalidate({ familyGroupId, dailyKey }) }); return <Card className="border-0 bg-gradient-to-br from-sky-50 via-white to-indigo-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><BookHeart className="h-5 w-5 text-indigo-700"/>家族のひとこと日記リレー</CardTitle><p className="text-xs text-slate-500">今日の一行をつないで、家族の小さな物語を残そう。</p></CardHeader><CardContent className="space-y-3"><div className="flex gap-2 rounded-xl bg-white/80 p-3"><Input value={entry} onChange={(event) => setEntry(event.target.value)} placeholder="例：夕方の空がきれいだった" maxLength={220}/><Button size="sm" disabled={!entry.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, dailyKey, entry })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>つなぐ</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-indigo-700">日記を読み込み中です…</p> : <div className="grid gap-2">{entries.map((item, index) => <article key={item.id} className={`rounded-xl p-3 shadow-sm ${item.isPassed ? "bg-indigo-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><p className={`text-sm ${item.isPassed ? "text-indigo-700 line-through" : "font-medium text-slate-800"}`}><span className="mr-2 text-xs font-bold text-indigo-500">{index + 1}</span>{item.entry}</p><button type="button" aria-label={item.isPassed ? "日記を戻す" : "次へつなぐ"} onClick={() => update.mutate({ familyGroupId, entryId: item.id, isPassed: !item.isPassed })} className={item.isPassed ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{entries.length === 0 && <p className="rounded-xl border border-dashed border-indigo-200 p-3 text-center text-xs text-slate-500">最初の一言を置いて、今日のリレーを始めましょう。</p>}</div>}</CardContent></Card>; }
