import { useState } from "react";
import { Check, HeartHandshake, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

export function FamilyCareBoard({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [title, setTitle] = useState(""); const [careTarget, setCareTarget] = useState(""); const [dueOn, setDueOn] = useState(""); const [assignedUserId, setAssignedUserId] = useState("unassigned");
  const { data: duties = [], isLoading } = trpc.careBoard.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const { data: members = [] } = trpc.family.getMembers.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const refresh = () => utils.careBoard.list.invalidate({ familyGroupId }); const create = trpc.careBoard.create.useMutation({ onSuccess: async () => { setTitle(""); setCareTarget(""); setDueOn(""); setAssignedUserId("unassigned"); await refresh(); } }); const complete = trpc.careBoard.complete.useMutation({ onSuccess: refresh });
  const memberNames = new Map(members.map((member) => [member.users.id, member.users.name ?? "家族"]));
  return <Card className="border-0 bg-gradient-to-br from-lime-50 via-white to-emerald-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><HeartHandshake className="h-5 w-5 text-lime-700"/>家族のケア当番ボード</CardTitle><p className="text-xs text-slate-500">ペット・植物・家の小さな世話を、やさしく引き継ぐ。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={careTarget} onChange={(event) => setCareTarget(event.target.value)} placeholder="世話するもの（例：ベランダの花）" maxLength={80}/><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="すること（例：水をあげる）" maxLength={180}/><div className="grid grid-cols-2 gap-2"><Input value={dueOn} onChange={(event) => setDueOn(event.target.value)} type="date" aria-label="期限"/><select value={assignedUserId} onChange={(event) => setAssignedUserId(event.target.value)} className="h-9 rounded-md border bg-white px-3 text-sm"><option value="unassigned">担当を決めない</option>{members.map((member) => <option key={member.users.id} value={member.users.id}>{member.users.name ?? "家族"}</option>)}</select></div><Button size="sm" disabled={!title.trim() || !careTarget.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, title, careTarget, assignedUserId: assignedUserId === "unassigned" ? undefined : Number(assignedUserId), dueOn: dueOn ? new Date(`${dueOn}T00:00:00`).toISOString() : undefined })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <Plus className="mr-1 h-4 w-4"/>}当番を追加</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-lime-700">当番を読み込み中です…</p> : <div className="grid gap-2">{duties.map((duty) => <button type="button" key={duty.id} onClick={() => complete.mutate({ familyGroupId, dutyId: duty.id, isDone: duty.status !== "done" })} className={`flex w-full items-start gap-2 rounded-xl p-3 text-left shadow-sm ${duty.status === "done" ? "bg-emerald-50 text-slate-400" : "bg-white text-slate-700"}`}><span className={`mt-0.5 grid h-5 w-5 place-items-center rounded-full border ${duty.status === "done" ? "border-emerald-500 bg-emerald-500 text-white" : "border-lime-400"}`}>{duty.status === "done" && <Check className="h-3.5 w-3.5"/>}</span><span><span className="text-[10px] text-lime-700">{duty.careTarget}</span><span className={`block text-sm font-semibold ${duty.status === "done" ? "line-through" : ""}`}>{duty.title}</span><span className="mt-1 block text-xs">{duty.assignedUserId ? `${memberNames.get(duty.assignedUserId) ?? "家族"}が担当` : "みんなで対応"}{duty.dueOn ? `・${new Date(duty.dueOn).toLocaleDateString()}まで` : ""}</span></span></button>)}{duties.length === 0 && <p className="rounded-xl border border-dashed border-lime-200 p-3 text-center text-xs text-slate-500">小さな世話を一つ、登録してみましょう。</p>}</div>}</CardContent></Card>;
}
