import { useState } from "react";
import { CheckCircle2, Loader2, MoonStar, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { bedtimePreparationKindLabels } from "@shared/familyWeeklyCareRituals";

type PreparationKind = keyof typeof bedtimePreparationKindLabels;
export function FamilyBedtimePreparationMemo({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [kind, setKind] = useState<PreparationKind>("bag"); const [memo, setMemo] = useState("");
  const { data: memos = [], isLoading } = trpc.bedtimePreparationMemos.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.bedtimePreparationMemos.create.useMutation({ onSuccess: async () => { setMemo(""); await utils.bedtimePreparationMemos.list.invalidate({ familyGroupId }); } });
  const update = trpc.bedtimePreparationMemos.update.useMutation({ onSuccess: () => utils.bedtimePreparationMemos.list.invalidate({ familyGroupId }) });
  return <Card className="border-0 bg-gradient-to-br from-indigo-950 via-indigo-900 to-slate-900 text-white shadow-lg"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base text-white"><MoonStar className="h-5 w-5 text-indigo-200"/>家族の寝る前準備メモ</CardTitle><p className="text-xs text-indigo-200">翌朝を少し楽にする準備を、家族で共有しよう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/10 p-3"><select value={kind} onChange={(event) => setKind(event.target.value as PreparationKind)} className="h-9 rounded-md border border-white/20 bg-white text-slate-800 px-3 text-sm"><option value="bag">かばん</option><option value="clothes">服</option><option value="plan">予定</option><option value="care">いたわり</option></select><div className="flex gap-2"><Input value={memo} onChange={(event) => setMemo(event.target.value)} placeholder="例：明日の体育着を玄関に置く" className="border-white/20 bg-white text-slate-800" maxLength={180}/><Button size="sm" disabled={!memo.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, kind, memo })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>残す</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-indigo-200">準備メモを読み込み中です…</p> : <div className="grid gap-2">{memos.map((entry) => <article key={entry.id} className={`rounded-xl p-3 ${entry.isPrepared ? "bg-emerald-500/20" : "bg-white/10"}`}><div className="flex items-start justify-between gap-2"><div><p className="text-[11px] font-medium text-indigo-200">{bedtimePreparationKindLabels[entry.kind]}</p><p className={`mt-1 text-sm ${entry.isPrepared ? "text-emerald-100 line-through" : "text-white"}`}>{entry.memo}</p></div><button type="button" aria-label={entry.isPrepared ? "未準備に戻す" : "準備できた"} onClick={() => update.mutate({ familyGroupId, memoId: entry.id, isPrepared: !entry.isPrepared })} className={entry.isPrepared ? "text-emerald-300" : "text-indigo-200"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{memos.length === 0 && <p className="rounded-xl border border-dashed border-indigo-300/40 p-3 text-center text-xs text-indigo-100">明日の自分を助ける、小さな準備を一つ残してみましょう。</p>}</div>}</CardContent></Card>;
}
