import { useState } from "react";
import { BellRing, CheckCircle2, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getReminderTone } from "@shared/familyWeeklyCare";

const toneLabel = { gentle: "いつでも大丈夫", soon: "そろそろ", today: "今日のこと" } as const;

export function FamilyGentleReminders({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [title, setTitle] = useState(""); const [note, setNote] = useState(""); const [dueDate, setDueDate] = useState("");
  const { data: reminders = [], isLoading } = trpc.gentleReminders.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.gentleReminders.create.useMutation({ onSuccess: async () => { setTitle(""); setNote(""); setDueDate(""); await utils.gentleReminders.list.invalidate({ familyGroupId }); } });
  const update = trpc.gentleReminders.update.useMutation({ onSuccess: () => utils.gentleReminders.list.invalidate({ familyGroupId }) });
  return <Card className="border-0 bg-gradient-to-br from-cyan-50 via-white to-sky-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><BellRing className="h-5 w-5 text-cyan-700"/>家族のやさしいリマインドカード</CardTitle><p className="text-xs text-slate-500">大切な用事を責めずに、短く共有しよう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例：図書館の本を返す" maxLength={160}/><div className="grid grid-cols-[minmax(0,1fr)_8rem] gap-2"><Input value={note} onChange={(event) => setNote(event.target.value)} placeholder="ひとこと（任意）" maxLength={240}/><Input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} aria-label="目安の日"/></div><Button size="sm" disabled={!title.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, title, note, dueAt: dueDate ? new Date(`${dueDate}T12:00:00`) : undefined })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>そっと知らせる</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-cyan-700">リマインドを読み込み中です…</p> : <div className="grid gap-2">{reminders.map((reminder) => { const tone = getReminderTone(reminder.dueAt); return <article key={reminder.id} className={`rounded-xl p-3 shadow-sm ${reminder.isCompleted ? "bg-slate-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm font-semibold ${reminder.isCompleted ? "text-slate-500 line-through" : "text-slate-800"}`}>{reminder.title}</p><p className="mt-0.5 text-[11px] text-cyan-700">{toneLabel[tone]}{reminder.dueAt ? ` · ${new Date(reminder.dueAt).toLocaleDateString()}` : ""}</p>{reminder.note && <p className="mt-1 text-xs text-slate-600">{reminder.note}</p>}</div><button type="button" disabled={update.isPending} aria-label={reminder.isCompleted ? "未完了に戻す" : "済んだ"} onClick={() => update.mutate({ familyGroupId, reminderId: reminder.id, isCompleted: !reminder.isCompleted })} className={reminder.isCompleted ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>; })}{reminders.length === 0 && <p className="rounded-xl border border-dashed border-cyan-200 p-3 text-center text-xs text-slate-500">忘れたくないことを、最初のやさしいカードにしてみましょう。</p>}</div>}</CardContent></Card>;
}
