import { useState } from "react";
import { ExternalLink, Loader2, Music2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getPlaylistMoodLabel, type PlaylistMood } from "@shared/familyDailyCare";

export function FamilyPlaylist({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils();
  const [title, setTitle] = useState(""); const [artist, setArtist] = useState(""); const [mood, setMood] = useState<PlaylistMood>("morning"); const [message, setMessage] = useState(""); const [linkUrl, setLinkUrl] = useState("");
  const { data: items = [], isLoading } = trpc.playlist.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.playlist.create.useMutation({ onSuccess: async () => { setTitle(""); setArtist(""); setMood("morning"); setMessage(""); setLinkUrl(""); await utils.playlist.list.invalidate({ familyGroupId }); } });
  return <Card className="border-0 bg-gradient-to-br from-fuchsia-50 via-white to-violet-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Music2 className="h-5 w-5 text-fuchsia-600"/>家族の一緒に作るプレイリスト</CardTitle><p className="text-xs text-slate-500">朝・帰宅・週末の気分に寄り添う曲を、一言とともに。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="曲名" maxLength={180}/><div className="grid grid-cols-[minmax(0,1fr)_6rem] gap-2"><Input value={artist} onChange={(event) => setArtist(event.target.value)} placeholder="アーティスト（任意）" maxLength={160}/><select value={mood} onChange={(event) => setMood(event.target.value as PlaylistMood)} className="h-9 rounded-md border bg-white px-2 text-sm"><option value="morning">朝</option><option value="homecoming">帰宅</option><option value="weekend">週末</option><option value="other">いつでも</option></select></div><Input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="この曲を届けたい理由（任意）" maxLength={240}/><Input value={linkUrl} onChange={(event) => setLinkUrl(event.target.value)} placeholder="楽曲リンク（任意）" type="url" maxLength={512}/><Button size="sm" disabled={!title.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, title, artist, mood, message, linkUrl: linkUrl || undefined })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>曲を追加</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-fuchsia-700">プレイリストを読み込み中です…</p> : <div className="grid gap-2">{items.slice(0, 6).map((item) => <article key={item.id} className="rounded-xl bg-white p-3 shadow-sm"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-semibold text-slate-800">{item.title}</p><p className="mt-0.5 text-[11px] text-fuchsia-700">{getPlaylistMoodLabel(item.mood)}{item.artist ? ` · ${item.artist}` : ""}</p></div>{item.linkUrl && <a href={item.linkUrl} target="_blank" rel="noreferrer" aria-label={`${item.title}を開く`} className="rounded-full p-1.5 text-fuchsia-600 hover:bg-fuchsia-50"><ExternalLink className="h-4 w-4"/></a>}</div>{item.message && <p className="mt-2 text-xs text-slate-600">{item.message}</p>}</article>)}{items.length === 0 && <p className="rounded-xl border border-dashed border-fuchsia-200 p-3 text-center text-xs text-slate-500">家族に聴いてほしい一曲を、最初に加えてみましょう。</p>}</div>}</CardContent></Card>;
}
