import { useState } from "react";
import { BookmarkCheck, CheckCircle2, Lightbulb, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countSavedDiscoveries } from "@shared/familyGentleWeekend";

export function FamilyDiscoveryShare({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [discovery, setDiscovery] = useState(""); const [sourceHint, setSourceHint] = useState(""); const { data: shares = [], isLoading } = trpc.discoveryShares.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.discoveryShares.create.useMutation({ onSuccess: async () => { setDiscovery(""); setSourceHint(""); await utils.discoveryShares.list.invalidate({ familyGroupId }); } }); const update = trpc.discoveryShares.update.useMutation({ onSuccess: () => utils.discoveryShares.list.invalidate({ familyGroupId }) }); return <Card className="border-0 bg-gradient-to-br from-amber-50 via-white to-yellow-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Lightbulb className="h-5 w-5 text-amber-600"/>家族の今日の発見シェア</CardTitle><p className="text-xs text-slate-500">新しく知ったことや気づいたことを、気軽に残そう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-amber-700"><BookmarkCheck className="mr-1 inline h-4 w-4"/>保存した発見：{countSavedDiscoveries(shares)}件</p><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={discovery} onChange={(event) => setDiscovery(event.target.value)} placeholder="例：月は毎日少しずつ同じ時間に遅く昇る" maxLength={240}/><div className="flex gap-2"><Input value={sourceHint} onChange={(event) => setSourceHint(event.target.value)} placeholder="どこで知った？（任意）" maxLength={120}/><Button size="sm" disabled={!discovery.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, discovery, sourceHint })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>共有</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-amber-700">発見を読み込み中です…</p> : <div className="grid gap-2">{shares.map((share) => <article key={share.id} className={`rounded-xl p-3 shadow-sm ${share.isSaved ? "bg-amber-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm ${share.isSaved ? "text-amber-700 line-through" : "text-slate-800"}`}>{share.discovery}</p>{share.sourceHint && <p className="mt-1 text-xs text-amber-800">{share.sourceHint}</p>}</div><button type="button" aria-label={share.isSaved ? "保存を外す" : "保存する"} onClick={() => update.mutate({ familyGroupId, shareId: share.id, isSaved: !share.isSaved })} className={share.isSaved ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{shares.length === 0 && <p className="rounded-xl border border-dashed border-amber-200 p-3 text-center text-xs text-slate-500">今日新しく知ったことを、一つだけ家族に渡してみましょう。</p>}</div>}</CardContent></Card>; }
