import { useState } from "react";
import { CheckCircle2, CircleHelp, Loader2, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countOpenQuestions } from "@shared/familyMorningWeekends";

export function FamilyQuestionBox({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [question, setQuestion] = useState(""); const [isAnonymous, setIsAnonymous] = useState(false);
  const { data: entries = [], isLoading } = trpc.questionBox.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.questionBox.create.useMutation({ onSuccess: async () => { setQuestion(""); await utils.questionBox.list.invalidate({ familyGroupId }); } });
  const update = trpc.questionBox.update.useMutation({ onSuccess: () => utils.questionBox.list.invalidate({ familyGroupId }) });
  return <Card className="border-0 bg-gradient-to-br from-cyan-50 via-white to-teal-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><CircleHelp className="h-5 w-5 text-teal-700"/>家族の小さな質問箱</CardTitle><p className="text-xs text-slate-500">聞いてみたいことを、会話の入口としてそっと集めよう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-teal-700">まだ開いていない質問：{countOpenQuestions(entries)}件</p><div className="rounded-xl bg-white/80 p-3"><div className="flex gap-2"><Input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="家族に聞いてみたいこと" maxLength={280}/><Button size="icon" aria-label="質問を入れる" disabled={!question.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, question, isAnonymous })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <Send className="h-4 w-4"/>}</Button></div><label className="mt-2 flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={isAnonymous} onChange={(event) => setIsAnonymous(event.target.checked)} className="h-4 w-4 accent-teal-600"/>名前を出さずに入れる</label></div>{isLoading ? <p className="py-3 text-center text-xs text-teal-700">質問を読み込み中です…</p> : <div className="grid gap-2">{entries.map((entry) => <article key={entry.id} className={`rounded-xl p-3 shadow-sm ${entry.isOpened ? "bg-slate-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className="text-[11px] font-medium text-teal-700">{entry.isAnonymous ? "匿名の質問" : "家族からの質問"}</p><p className={`mt-1 text-sm ${entry.isOpened ? "text-slate-500" : "font-semibold text-slate-800"}`}>{entry.question}</p></div><button type="button" aria-label={entry.isOpened ? "未読に戻す" : "読んだ"} onClick={() => update.mutate({ familyGroupId, entryId: entry.id, isOpened: !entry.isOpened })} className={entry.isOpened ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{entries.length === 0 && <p className="rounded-xl border border-dashed border-teal-200 p-3 text-center text-xs text-slate-500">ちょっと聞いてみたいことを、一つ入れてみましょう。</p>}</div>}</CardContent></Card>;
}
