import { useState } from "react";
import { Dices, Loader2, Plus, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { pickFamilyFunPrompt } from "@shared/familyFun";

export function FamilyFunLottery({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [content, setContent] = useState(""); const [theme, setTheme] = useState(""); const [selectedId, setSelectedId] = useState<number | null>(null);
  const { data: prompts = [], isLoading } = trpc.funLottery.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.funLottery.create.useMutation({ onSuccess: async () => { setContent(""); setTheme(""); await utils.funLottery.list.invalidate({ familyGroupId }); } }); const selected = prompts.find((prompt) => prompt.id === selectedId);
  return <Card className="border-0 bg-gradient-to-br from-fuchsia-50 via-white to-pink-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Dices className="h-5 w-5 text-fuchsia-600"/>家族のお楽しみくじ</CardTitle><p className="text-xs text-slate-500">小さな遊びや会話のきっかけを、今日ひとつ引いてみよう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={content} onChange={(event) => setContent(event.target.value)} placeholder="例：今日いちばん笑ったことを話す" maxLength={240}/><Input value={theme} onChange={(event) => setTheme(event.target.value)} placeholder="テーマ（例：会話）" maxLength={80}/><Button size="sm" disabled={!content.trim() || !theme.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, content, theme })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>くじを追加</>}</Button></div><Button className="w-full bg-gradient-to-r from-fuchsia-500 to-pink-500 text-white" disabled={prompts.length === 0} onClick={() => setSelectedId(pickFamilyFunPrompt(prompts)?.id ?? null)}><Dices className="mr-1 h-4 w-4"/>今日のくじを引く</Button>{selected && <div className="rounded-xl bg-fuchsia-100 p-4 text-center"><Sparkles className="mx-auto mb-1 h-5 w-5 text-fuchsia-600"/><p className="text-[11px] text-fuchsia-700">{selected.theme}</p><p className="text-sm font-semibold text-slate-800">{selected.content}</p></div>}{isLoading ? <p className="py-3 text-center text-xs text-fuchsia-700">くじを読み込み中です…</p> : <div className="flex flex-wrap gap-1.5">{prompts.map((prompt) => <span key={prompt.id} className="rounded-full bg-fuchsia-100 px-2 py-1 text-[11px] text-fuchsia-800">{prompt.theme}</span>)}{prompts.length === 0 && <p className="w-full rounded-xl border border-dashed border-fuchsia-200 p-3 text-center text-xs text-slate-500">家族のお楽しみを、一つ追加してみましょう。</p>}</div>}</CardContent></Card>;
}
