import { useState } from "react";
import { BookHeart, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

export function FamilyCareMessageBoard({ familyGroupId, currentUserId }: { familyGroupId: number; currentUserId?: number }) {
  const utils = trpc.useUtils(); const [message, setMessage] = useState(""); const [recipientUserId, setRecipientUserId] = useState("all");
  const { data: messages = [], isLoading } = trpc.careMessages.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const { data: members = [] } = trpc.family.getMembers.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const refresh = () => utils.careMessages.list.invalidate({ familyGroupId });
  const create = trpc.careMessages.create.useMutation({ onSuccess: async () => { setMessage(""); await refresh(); } }); const markRead = trpc.careMessages.markRead.useMutation({ onSuccess: refresh });
  const nameMap = new Map(members.map((member) => [member.users.id, member.users.name ?? "家族"]));
  return <Card className="border-0 bg-gradient-to-br from-sky-50 via-white to-cyan-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><BookHeart className="h-5 w-5 text-sky-600"/>家族の見守りメッセージ帳</CardTitle><p className="text-xs text-slate-500">短い気づかいを残して、既読を静かに見守ります。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="例：気をつけて帰ってきてね" maxLength={180}/><select value={recipientUserId} onChange={(event) => setRecipientUserId(event.target.value)} className="h-9 rounded-md border bg-white px-3 text-sm"><option value="all">みんなへ</option>{members.map((member) => <option key={member.users.id} value={member.users.id}>{member.users.name ?? "家族"}</option>)}</select><Button size="sm" disabled={!message.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, message, recipientUserId: recipientUserId === "all" ? undefined : Number(recipientUserId) })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>メッセージを残す</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-sky-700">メッセージを読み込み中です…</p> : <div className="grid gap-2">{messages.map((entry) => <button type="button" key={entry.id} onClick={() => !entry.isRead && markRead.mutate({ familyGroupId, messageId: entry.id })} className={`rounded-xl p-3 text-left shadow-sm ${entry.isRead ? "bg-white text-slate-500" : "bg-sky-100 text-slate-800"}`}><p className="text-[11px] text-sky-700">{nameMap.get(entry.senderUserId) ?? "家族"} → {entry.recipientUserId ? nameMap.get(entry.recipientUserId) ?? "家族" : "みんな"}</p><p className="mt-1 text-sm font-semibold">{entry.message}</p><p className="mt-1 text-[11px]">{entry.isRead ? "既読" : currentUserId && entry.senderUserId !== currentUserId ? "タップで既読にする" : "未読"}</p></button>)}{messages.length === 0 && <p className="rounded-xl border border-dashed border-sky-200 p-3 text-center text-xs text-slate-500">今日の気づかいを、ひとこと残してみましょう。</p>}</div>}</CardContent></Card>;
}
