import { useState } from "react";
import { Camera, CheckCircle2, Loader2, Plus, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getMonthKey } from "@shared/familyTomorrowFlow";

export function FamilySeasonalPhotoPrompt({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [monthKey] = useState(() => getMonthKey()); const [theme, setTheme] = useState(""); const [detail, setDetail] = useState("");
  const { data: prompts = [], isLoading } = trpc.seasonalPhotoPrompts.list.useQuery({ familyGroupId, monthKey }, { enabled: familyGroupId > 0 });
  const create = trpc.seasonalPhotoPrompts.create.useMutation({ onSuccess: async () => { setTheme(""); setDetail(""); await utils.seasonalPhotoPrompts.list.invalidate({ familyGroupId, monthKey }); } });
  const update = trpc.seasonalPhotoPrompts.update.useMutation({ onSuccess: () => utils.seasonalPhotoPrompts.list.invalidate({ familyGroupId, monthKey }) });
  return <Card className="border-0 bg-gradient-to-br from-fuchsia-50 via-white to-rose-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Camera className="h-5 w-5 text-fuchsia-700"/>家族の季節フォトお題</CardTitle><p className="text-xs text-slate-500">今月の小さな写真テーマで、思い出集めを楽しもう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={theme} onChange={(event) => setTheme(event.target.value)} placeholder="例：いちばん好きな夏の色" maxLength={160}/><div className="flex gap-2"><Input value={detail} onChange={(event) => setDetail(event.target.value)} placeholder="ひとことヒント（任意）" maxLength={240}/><Button size="sm" disabled={!theme.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, monthKey, theme, detail })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>出す</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-fuchsia-700">フォトお題を読み込み中です…</p> : <div className="grid gap-2">{prompts.map((prompt) => <article key={prompt.id} className={`rounded-xl p-3 shadow-sm ${prompt.isActive ? "bg-white" : "bg-slate-50"}`}><div className="flex items-start justify-between gap-2"><div><p className={`flex items-center gap-1 text-sm font-semibold ${prompt.isActive ? "text-slate-800" : "text-slate-500 line-through"}`}><Sparkles className="h-4 w-4 text-fuchsia-600"/>{prompt.theme}</p>{prompt.detail && <p className="mt-1 text-xs text-slate-600">{prompt.detail}</p>}</div><button type="button" aria-label={prompt.isActive ? "お題を完了にする" : "お題を再開する"} onClick={() => update.mutate({ familyGroupId, promptId: prompt.id, isActive: !prompt.isActive })} className={prompt.isActive ? "text-slate-400" : "text-emerald-600"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{prompts.length === 0 && <p className="rounded-xl border border-dashed border-fuchsia-200 p-3 text-center text-xs text-slate-500">今月らしい一枚を撮るための、楽しいお題を決めましょう。</p>}</div>}</CardContent></Card>;
}
