import { useState } from "react";
import { CheckCircle2, FlaskConical, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countKeptTrials } from "@shared/familyCareFlow";

export function FamilyTriedMemo({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [triedThing, setTriedThing] = useState(""); const [reflection, setReflection] = useState(""); const { data: memos = [], isLoading } = trpc.triedMemos.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.triedMemos.create.useMutation({ onSuccess: async () => { setTriedThing(""); setReflection(""); await utils.triedMemos.list.invalidate({ familyGroupId }); } }); const update = trpc.triedMemos.update.useMutation({ onSuccess: () => utils.triedMemos.list.invalidate({ familyGroupId }) }); return <Card className="border-0 bg-gradient-to-br from-amber-50 via-white to-yellow-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><FlaskConical className="h-5 w-5 text-amber-600"/>家族のやってみたメモ</CardTitle><p className="text-xs text-slate-500">試してみたことと感想を短く残して、次の一歩につなげよう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-amber-700">残しておきたい試み：{countKeptTrials(memos)}件</p><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={triedThing} onChange={(event) => setTriedThing(event.target.value)} placeholder="例：朝に5分だけ散歩してみた" maxLength={180}/><div className="flex gap-2"><Input value={reflection} onChange={(event) => setReflection(event.target.value)} placeholder="どうだった？（任意）" maxLength={240}/><Button size="sm" disabled={!triedThing.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, triedThing, reflection })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>残す</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-amber-700">やってみたメモを読み込み中です…</p> : <div className="grid gap-2">{memos.map((memo) => <article key={memo.id} className={`rounded-xl p-3 shadow-sm ${memo.isKept ? "bg-amber-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm ${memo.isKept ? "text-amber-700 line-through" : "font-semibold text-slate-800"}`}>{memo.triedThing}</p>{memo.reflection && <p className="mt-1 text-xs text-amber-800">{memo.reflection}</p>}</div><button type="button" aria-label={memo.isKept ? "保存を外す" : "残しておく"} onClick={() => update.mutate({ familyGroupId, memoId: memo.id, isKept: !memo.isKept })} className={memo.isKept ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{memos.length === 0 && <p className="rounded-xl border border-dashed border-amber-200 p-3 text-center text-xs text-slate-500">今日試してみた小さなことを、一つ書き留めてみましょう。</p>}</div>}</CardContent></Card>; }
