import { useState } from "react";
import { CheckCircle2, Loader2, Plus, Repeat2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countReadyRelays } from "@shared/familyDailyContinuity";

export function FamilyTomorrowPreparationRelay({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [preparation, setPreparation] = useState(""); const [relayNote, setRelayNote] = useState(""); const { data: relays = [], isLoading } = trpc.tomorrowPreparationRelays.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.tomorrowPreparationRelays.create.useMutation({ onSuccess: async () => { setPreparation(""); setRelayNote(""); await utils.tomorrowPreparationRelays.list.invalidate({ familyGroupId }); } }); const update = trpc.tomorrowPreparationRelays.update.useMutation({ onSuccess: () => utils.tomorrowPreparationRelays.list.invalidate({ familyGroupId }) }); return <Card className="border-0 bg-gradient-to-br from-teal-50 via-white to-emerald-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Repeat2 className="h-5 w-5 text-teal-700"/>家族の明日の準備リレー</CardTitle><p className="text-xs text-slate-500">翌日の小さな準備を引き継ぎ、家族で支え合おう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-teal-700">準備できたリレー：{countReadyRelays(relays)}件</p><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={preparation} onChange={(event) => setPreparation(event.target.value)} placeholder="例：明日の水筒を洗っておく" maxLength={180}/><div className="flex gap-2"><Input value={relayNote} onChange={(event) => setRelayNote(event.target.value)} placeholder="引き継ぎのひとこと（任意）" maxLength={180}/><Button size="sm" disabled={!preparation.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, preparation, relayNote })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>渡す</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-teal-700">準備リレーを読み込み中です…</p> : <div className="grid gap-2">{relays.map((entry) => <article key={entry.id} className={`rounded-xl p-3 shadow-sm ${entry.isReady ? "bg-teal-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm ${entry.isReady ? "text-teal-700 line-through" : "font-semibold text-slate-800"}`}>{entry.preparation}</p>{entry.relayNote && <p className="mt-1 text-xs text-teal-800">{entry.relayNote}</p>}</div><button type="button" aria-label={entry.isReady ? "未準備に戻す" : "準備できた"} onClick={() => update.mutate({ familyGroupId, relayId: entry.id, isReady: !entry.isReady })} className={entry.isReady ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{relays.length === 0 && <p className="rounded-xl border border-dashed border-teal-200 p-3 text-center text-xs text-slate-500">明日の朝を少し助ける準備を、一つリレーしてみましょう。</p>}</div>}</CardContent></Card>; }
