import { useState } from "react";
import { HeartPulse, Loader2, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { wellbeingStateLabels } from "@shared/familyEverydayGood";

type WellbeingState = keyof typeof wellbeingStateLabels;
export function FamilyWellbeingNote({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [state, setState] = useState<WellbeingState>("good"); const [supportNeed, setSupportNeed] = useState(""); const { data: notes = [], isLoading } = trpc.wellbeingNotes.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.wellbeingNotes.create.useMutation({ onSuccess: async () => { setSupportNeed(""); await utils.wellbeingNotes.list.invalidate({ familyGroupId }); } }); return <Card className="border-0 bg-gradient-to-br from-sky-50 via-white to-cyan-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><HeartPulse className="h-5 w-5 text-sky-700"/>家族のゆるい体調ひとこと</CardTitle><p className="text-xs text-slate-500">診断ではなく、今の状態とほしい配慮を短く伝えよう。</p></CardHeader><CardContent className="space-y-3"><div className="rounded-xl bg-white/80 p-3"><div className="grid grid-cols-4 gap-1">{(Object.keys(wellbeingStateLabels) as WellbeingState[]).map((key) => <button key={key} type="button" onClick={() => setState(key)} className={`rounded-lg px-1 py-2 text-[10px] transition active:scale-95 ${state === key ? "bg-sky-600 text-white" : "bg-sky-50 text-sky-800"}`}>{wellbeingStateLabels[key]}</button>)}</div><div className="mt-2 flex gap-2"><Input value={supportNeed} onChange={(event) => setSupportNeed(event.target.value)} placeholder="今ほしい配慮（任意）" maxLength={180}/><Button size="icon" aria-label="体調ひとことを送る" disabled={create.isPending} onClick={() => create.mutate({ familyGroupId, state, supportNeed })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <Send className="h-4 w-4"/>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-sky-700">体調ひとことを読み込み中です…</p> : <div className="grid gap-2">{notes.slice(0, 4).map((note) => <article key={note.id} className="rounded-xl bg-white p-3 shadow-sm"><p className="text-xs font-medium text-sky-800">{wellbeingStateLabels[note.state]}</p>{note.supportNeed && <p className="mt-1 text-sm text-slate-800">{note.supportNeed}</p>}</article>)}{notes.length === 0 && <p className="rounded-xl border border-dashed border-sky-200 p-3 text-center text-xs text-slate-500">今日の自分に必要な配慮を、一言だけ伝えてみましょう。</p>}</div>}</CardContent></Card>; }
