import { useState } from "react";
import { CheckCircle2, Loader2, PackageOpen, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getRescueUrgencyLabel, type RescueUrgency } from "@shared/familyDailyCare";

export function FamilyForgottenItemRescue({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils();
  const [itemName, setItemName] = useState(""); const [note, setNote] = useState(""); const [urgency, setUrgency] = useState<RescueUrgency>("soon");
  const { data: alerts = [], isLoading } = trpc.forgottenItems.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.forgottenItems.create.useMutation({ onSuccess: async () => { setItemName(""); setNote(""); setUrgency("soon"); await utils.forgottenItems.list.invalidate({ familyGroupId }); } });
  const resolve = trpc.forgottenItems.resolve.useMutation({ onSuccess: () => utils.forgottenItems.list.invalidate({ familyGroupId }) });
  return <Card className="border-0 bg-gradient-to-br from-rose-50 via-white to-orange-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><PackageOpen className="h-5 w-5 text-rose-600"/>家族の忘れものレスキュー</CardTitle><p className="text-xs text-slate-500">出発前に気づいた持ち物を、責めずにそっと知らせ合おう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><div className="grid grid-cols-[minmax(0,1fr)_5.5rem] gap-2"><Input value={itemName} onChange={(event) => setItemName(event.target.value)} placeholder="例：水筒、鍵、連絡帳" maxLength={160}/><select value={urgency} onChange={(event) => setUrgency(event.target.value as RescueUrgency)} className="h-9 rounded-md border bg-white px-2 text-sm"><option value="soon">気づいたら</option><option value="urgent">急ぎ</option></select></div><Input value={note} onChange={(event) => setNote(event.target.value)} placeholder="ひとこと（任意）" maxLength={240}/><Button size="sm" disabled={!itemName.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, itemName, note, urgency })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>レスキューを出す</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-rose-700">レスキューを読み込み中です…</p> : <div className="grid gap-2">{alerts.map((alert) => <article key={alert.id} className={`rounded-xl p-3 shadow-sm ${alert.isResolved ? "bg-slate-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm font-semibold ${alert.isResolved ? "text-slate-500 line-through" : "text-slate-800"}`}>{alert.itemName}</p><p className="mt-0.5 text-[11px] text-rose-700">{getRescueUrgencyLabel(alert.urgency)}</p>{alert.note && <p className="mt-1 text-xs text-slate-600">{alert.note}</p>}</div><button type="button" aria-label={alert.isResolved ? "未解決に戻す" : "解決済みにする"} disabled={resolve.isPending} onClick={() => resolve.mutate({ familyGroupId, alertId: alert.id, isResolved: !alert.isResolved })} className={alert.isResolved ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{alerts.length === 0 && <p className="rounded-xl border border-dashed border-rose-200 p-3 text-center text-xs text-slate-500">気づいた持ち物を、必要なときに共有できます。</p>}</div>}</CardContent></Card>;
}
