import { useState } from "react";
import { CalendarDays, Loader2, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getWeekStartKey } from "@shared/familyDailyContinuity";

export function FamilyWeekStartDeclaration({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [weekKey] = useState(() => getWeekStartKey()); const [declaration, setDeclaration] = useState(""); const { data: entries = [], isLoading } = trpc.weekStartDeclarations.list.useQuery({ familyGroupId, weekKey }, { enabled: familyGroupId > 0 }); const create = trpc.weekStartDeclarations.create.useMutation({ onSuccess: async () => { setDeclaration(""); await utils.weekStartDeclarations.list.invalidate({ familyGroupId, weekKey }); } }); return <Card className="border-0 bg-gradient-to-br from-violet-50 via-white to-indigo-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="h-5 w-5 text-violet-700"/>家族の週はじめ宣言</CardTitle><p className="text-xs text-slate-500">週の最初に、今週大切にしたい自分の気持ちを短く共有しよう。</p></CardHeader><CardContent className="space-y-3"><div className="flex gap-2 rounded-xl bg-white/80 p-3"><Input value={declaration} onChange={(event) => setDeclaration(event.target.value)} placeholder="例：無理せず、少しずつ進める" maxLength={180}/><Button size="icon" aria-label="週はじめ宣言を送る" disabled={!declaration.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, weekKey, declaration })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <Send className="h-4 w-4"/>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-violet-700">宣言を読み込み中です…</p> : <div className="grid gap-2">{entries.map((entry) => <article key={entry.id} className="rounded-xl bg-white p-3 shadow-sm"><p className="text-sm text-slate-800">{entry.declaration}</p></article>)}{entries.length === 0 && <p className="rounded-xl border border-dashed border-violet-200 p-3 text-center text-xs text-slate-500">今週の自分にかけたい一言を、最初に残してみましょう。</p>}</div>}</CardContent></Card>; }
