import { useState } from "react";
import { CheckCircle2, Flag, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countUnresolved } from "@shared/familyPriorityFlow";

export function FamilyPriorityMemo({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [priority, setPriority] = useState(""); const [note, setNote] = useState(""); const { data: memos = [], isLoading } = trpc.priorityMemos.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.priorityMemos.create.useMutation({ onSuccess: async () => { setPriority(""); setNote(""); await utils.priorityMemos.list.invalidate({ familyGroupId }); } }); const update = trpc.priorityMemos.update.useMutation({ onSuccess: () => utils.priorityMemos.list.invalidate({ familyGroupId }) }); return <Card className="border-0 bg-gradient-to-br from-red-50 via-white to-orange-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Flag className="h-5 w-5 text-red-600"/>家族の優先メモ</CardTitle><p className="text-xs text-slate-500">今日・今週で見落としたくないことを、先に共有しよう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-red-700">未解決：{countUnresolved(memos)}件</p><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={priority} onChange={(event) => setPriority(event.target.value)} placeholder="例：木曜は提出物を忘れない" maxLength={180}/><div className="flex gap-2"><Input value={note} onChange={(event) => setNote(event.target.value)} placeholder="補足（任意）" maxLength={240}/><Button size="sm" disabled={!priority.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, priority, note })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>置く</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-red-700">優先メモを読み込み中です…</p> : <div className="grid gap-2">{memos.map((memo) => <article key={memo.id} className={`rounded-xl p-3 shadow-sm ${memo.isResolved ? "bg-red-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm ${memo.isResolved ? "text-red-700 line-through" : "font-semibold text-slate-800"}`}>{memo.priority}</p>{memo.note && <p className="mt-1 text-xs text-red-800">{memo.note}</p>}</div><button type="button" aria-label={memo.isResolved ? "未解決に戻す" : "解決にする"} onClick={() => update.mutate({ familyGroupId, memoId: memo.id, isResolved: !memo.isResolved })} className={memo.isResolved ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{memos.length === 0 && <p className="rounded-xl border border-dashed border-red-200 p-3 text-center text-xs text-slate-500">大切なことを一つ、先に置いておきましょう。</p>}</div>}</CardContent></Card>; }
