import { useState } from "react";
import { CheckCircle2, Lightbulb, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { countPendingPicks } from "@shared/familyEverydayPicks";

export function FamilyHouseholdTip({ familyGroupId }: { familyGroupId: number }) { const utils = trpc.useUtils(); const [tip, setTip] = useState(""); const [category, setCategory] = useState(""); const { data: tips = [], isLoading } = trpc.householdTips.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 }); const create = trpc.householdTips.create.useMutation({ onSuccess: async () => { setTip(""); setCategory(""); await utils.householdTips.list.invalidate({ familyGroupId }); } }); const update = trpc.householdTips.update.useMutation({ onSuccess: () => utils.householdTips.list.invalidate({ familyGroupId }) }); return <Card className="border-0 bg-gradient-to-br from-yellow-50 via-white to-amber-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Lightbulb className="h-5 w-5 text-amber-600"/>家族の家しごとコツ共有</CardTitle><p className="text-xs text-slate-500">暮らしの小さな工夫を共有して、役立ったら印を付けよう。</p></CardHeader><CardContent className="space-y-3"><p className="text-xs font-medium text-amber-700">試したいコツ：{countPendingPicks(tips.map((item) => ({ isHelpful: item.isHelpful })))}件</p><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={tip} onChange={(event) => setTip(event.target.value)} placeholder="例：洗濯物は取り込んだらすぐ畳む" maxLength={180}/><div className="flex gap-2"><Input value={category} onChange={(event) => setCategory(event.target.value)} placeholder="分類（任意）" maxLength={80}/><Button size="sm" disabled={!tip.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, tip, category })}>{create.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>共有</>}</Button></div></div>{isLoading ? <p className="py-3 text-center text-xs text-amber-700">コツを読み込み中です…</p> : <div className="grid gap-2">{tips.map((item) => <article key={item.id} className={`rounded-xl p-3 shadow-sm ${item.isHelpful ? "bg-amber-50" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm ${item.isHelpful ? "text-amber-700 line-through" : "font-semibold text-slate-800"}`}>{item.tip}</p>{item.category && <p className="mt-1 text-xs text-amber-800">{item.category}</p>}</div><button type="button" aria-label={item.isHelpful ? "未評価に戻す" : "役立った"} onClick={() => update.mutate({ familyGroupId, tipId: item.id, isHelpful: !item.isHelpful })} className={item.isHelpful ? "text-emerald-600" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{tips.length === 0 && <p className="rounded-xl border border-dashed border-amber-200 p-3 text-center text-xs text-slate-500">暮らしが少し楽になるコツを、一つ残してみましょう。</p>}</div>}</CardContent></Card>; }
