import { useState } from "react";
import { CloudSun, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getWeatherLabel, getWeatherPackingHint, type WeatherKind } from "@shared/familyDailyCheckins";

export function FamilyWeatherMemo({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils();
  const [weather, setWeather] = useState<WeatherKind>("sunny"); const [clothingNote, setClothingNote] = useState(""); const [carryingNote, setCarryingNote] = useState(""); const [bodyNote, setBodyNote] = useState("");
  const { data: memos = [], isLoading } = trpc.weatherMemos.list.useQuery({ familyGroupId }, { enabled: familyGroupId > 0 });
  const create = trpc.weatherMemos.create.useMutation({ onSuccess: async () => { setClothingNote(""); setCarryingNote(""); setBodyNote(""); await utils.weatherMemos.list.invalidate({ familyGroupId }); } });
  return <Card className="border-0 bg-gradient-to-br from-sky-50 via-white to-cyan-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><CloudSun className="h-5 w-5 text-sky-600"/>家族のお天気じぶんごとメモ</CardTitle><p className="text-xs text-slate-500">その日の天気に合わせた、服装・持ち物・体の気づきを共有。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><select value={weather} onChange={(event) => setWeather(event.target.value as WeatherKind)} className="h-9 rounded-md border bg-white px-3 text-sm"><option value="sunny">晴れ</option><option value="cloudy">くもり</option><option value="rainy">雨</option><option value="cold">寒い</option><option value="hot">暑い</option><option value="other">そのほか</option></select><p className="text-[11px] text-sky-700">ヒント：{getWeatherPackingHint(weather)}</p><Input value={clothingNote} onChange={(event) => setClothingNote(event.target.value)} placeholder="服装メモ（任意）" maxLength={180}/><Input value={carryingNote} onChange={(event) => setCarryingNote(event.target.value)} placeholder="持ち物メモ（任意）" maxLength={180}/><Input value={bodyNote} onChange={(event) => setBodyNote(event.target.value)} placeholder="体の気づき（任意）" maxLength={180}/><Button size="sm" disabled={create.isPending} onClick={() => create.mutate({ familyGroupId, weather, clothingNote, carryingNote, bodyNote })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>気づきを残す</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-sky-700">お天気メモを読み込み中です…</p> : <div className="grid gap-2">{memos.slice(0, 4).map((memo) => <article key={memo.id} className="rounded-xl bg-white p-3 shadow-sm"><p className="text-sm font-semibold text-sky-800">{getWeatherLabel(memo.weather)}</p><p className="mt-1 text-xs text-slate-600">{[memo.clothingNote, memo.carryingNote, memo.bodyNote].filter(Boolean).join(" · ") || "ひとことメモなし"}</p></article>)}{memos.length === 0 && <p className="rounded-xl border border-dashed border-sky-200 p-3 text-center text-xs text-slate-500">今日の空と体の気づきを、最初に残してみましょう。</p>}</div>}</CardContent></Card>;
}
