import { useState } from "react";
import { CheckCircle2, Goal, Loader2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { getGoalCompletionRate, getMonthKey } from "@shared/familyMindfulMoments";

export function FamilyMonthlyGoals({ familyGroupId }: { familyGroupId: number }) {
  const utils = trpc.useUtils(); const [title, setTitle] = useState(""); const [encouragement, setEncouragement] = useState(""); const monthKey = getMonthKey();
  const { data: goals = [], isLoading } = trpc.monthlyGoals.list.useQuery({ familyGroupId, monthKey }, { enabled: familyGroupId > 0 });
  const create = trpc.monthlyGoals.create.useMutation({ onSuccess: async () => { setTitle(""); setEncouragement(""); await utils.monthlyGoals.list.invalidate({ familyGroupId, monthKey }); } });
  const update = trpc.monthlyGoals.update.useMutation({ onSuccess: () => utils.monthlyGoals.list.invalidate({ familyGroupId, monthKey }) });
  return <Card className="border-0 bg-gradient-to-br from-lime-50 via-white to-emerald-50 shadow-md"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Goal className="h-5 w-5 text-lime-700"/>家族の今月の目標ボード</CardTitle><p className="text-xs text-slate-500">小さな目標を、応援の言葉とともに共有しよう。</p></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 rounded-xl bg-white/80 p-3"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例：毎日5分、本を読む" maxLength={160}/><Input value={encouragement} onChange={(event) => setEncouragement(event.target.value)} placeholder="応援のひとこと（任意）" maxLength={240}/><Button size="sm" disabled={!title.trim() || create.isPending} onClick={() => create.mutate({ familyGroupId, monthKey, title, encouragement })}>{create.isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin"/> : <><Plus className="mr-1 h-4 w-4"/>目標を追加</>}</Button></div>{isLoading ? <p className="py-3 text-center text-xs text-lime-700">目標を読み込み中です…</p> : <><p className="text-xs font-medium text-lime-800">今月の達成率：{getGoalCompletionRate(goals)}%</p><div className="grid gap-2">{goals.map((goal) => <article key={goal.id} className={`rounded-xl p-3 shadow-sm ${goal.isCompleted ? "bg-lime-100" : "bg-white"}`}><div className="flex items-start justify-between gap-2"><div><p className={`text-sm font-semibold ${goal.isCompleted ? "text-lime-900 line-through" : "text-slate-800"}`}>{goal.title}</p>{goal.encouragement && <p className="mt-1 text-xs text-slate-600">{goal.encouragement}</p>}</div><button type="button" disabled={update.isPending} aria-label={goal.isCompleted ? "未達成に戻す" : "達成にする"} onClick={() => update.mutate({ familyGroupId, goalId: goal.id, isCompleted: !goal.isCompleted })} className={goal.isCompleted ? "text-lime-700" : "text-slate-400"}><CheckCircle2 className="h-5 w-5"/></button></div></article>)}{goals.length === 0 && <p className="rounded-xl border border-dashed border-lime-200 p-3 text-center text-xs text-slate-500">今月やってみたい小さなことを一つ書いてみましょう。</p>}</div></>}</CardContent></Card>;
}
